services:
  client:
    container_name: client
    build: 
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - .env
    # networks:
    #   - my_network
  
  backend:
    container_name: server
    build: 
      context: .
      dockerfile: ./apps/backend/Dockerfile
    # restart: always
    ports:
      - "6969:6969"
    env_file:
      - .env
    # networks:
    #   - my_network
  
  ws-backend:
    container_name: ws-server
    build: 
      context: .
      dockerfile: ./apps/ws-backend/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    # networks:
    #   - my_network


# networks:
#   my_network: 
#     external: true  